package org.zifts.homepagegenerator.servlet;

/**
* This file was generated by IBM WebSphere Studio Version 3.5
* i:\wsstudio\BIN\GenerationStyleSheets\V3.5\JSP1.0\ServletModel\JavaServlet.xsl stylesheet was used to generate this file.
*
* 
*
*/ 
// Imports
//import com.ibm.servlet.*;
//import com.ibm.webtools.runtime.*;

import java.io.Serializable;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.zifts.homepagegenerator.util.ActualPicture;
import org.zifts.homepagegenerator.util.DirContent;
import org.zifts.homepagegenerator.util.UrlaubViewBean;


public class InitMenuServlet extends HttpServlet implements Serializable

{

  /*****************************************************************************
  * Process incoming requests for information
  * 
  * @param request Object that encapsulates the request to the servlet
  * @param response Object that encapsulates the response from the servlet
  * this servlet sets the current picture in the content frame
  * to the recieved Parameter actualPicture ...
  */
  public void doGet(HttpServletRequest request, HttpServletResponse response)
  {

	performTask(request, response);     
	
  }                                                                                  
  /*****************************************************************************
  * Process incoming requests for information
  * 
  * @param request Object that encapsulates the request to the servlet
  * @param response Object that encapsulates the response from the servlet
  * this servlet sets the current picture in the content frame
  * to the recieved Parameter actualPicture ...
  */
  public void doPost(HttpServletRequest request, HttpServletResponse response)
  {

	performTask(request, response);     
	
  }                                                                                
  /*****************************************************************************
  * Process incoming requests for information
  * 
  * @param request Object that encapsulates the request to the servlet
  * @param response Object that encapsulates the response from the servlet
  */
  public void performTask(HttpServletRequest request, HttpServletResponse response)
  {

  
	try 
	{

	  HttpSession session = request.getSession(true);
	  session.invalidate();
	  session = request.getSession(true);
	  // this deletes all objects stored at the moment
	  
	  UrlaubViewBean urlaubViewBean = new UrlaubViewBean();
	  session.setAttribute("urlaubViewBean", urlaubViewBean);
	  String urlaub= new String();
	  String path = new String();
	  String bilderRoot = new String();
	  
	  // instantiate the beans and store them so they can be accessed by the called page
	  DirContent dirContent = new DirContent();      
	  session.setAttribute("dirContent", dirContent);

	  //bilderRoot = getParameter(request, "bilderRoot", true, true, true, null);
	  //urlaub = getParameter(request, "urlaub", true, true, true, null);
	  bilderRoot = getServletConfig().getInitParameter("bilderRoot");
	  urlaub = request.getParameter("urlaub");
	  if (urlaub.equals("2001Wintour") )
	  {
		 path = getServletConfig().getInitParameter("2001Wintour");
	  }
	  if (urlaub.equals("2000USA") )
	  {
		 path = getServletConfig().getInitParameter("2000USA");
	  }
	  if (urlaub.equals("2000Canada") )
	  {
		 path = getServletConfig().getInitParameter("2000Canada");
	  }
	  else if (urlaub.equals("2000Wintour") )
	  {
		 path = getServletConfig().getInitParameter("2000Wintour");
	  }
	  else if (urlaub.equals("1999Schweiz") )
	  {
		 path = getServletConfig().getInitParameter("1999Schweiz");
	  }
	  else if (urlaub.equals("1998island") )
	  {
		 path = getServletConfig().getInitParameter("1998island");
	  }
	  else if (urlaub.equals("1996euseeland") )
	  {
		 path = getServletConfig().getInitParameter("1996neuseeland");
	  }
	  else if (urlaub.equals("1997oetztalerRadmarathon") )
	  {
		 path = getServletConfig().getInitParameter("1997oetztalerRadmarathon");
	  }
	  else if (urlaub.equals("1997skitourWeiskugel") )
	  {
		 path = getServletConfig().getInitParameter("1997skitourWeiskugel");
	  }
	  else if (urlaub.equals("1997lofoten") )
	  {
		 path = getServletConfig().getInitParameter("1997lofoten");
	  }
	  else if (urlaub.equals("1988bund") )
	  {
		 path = getServletConfig().getInitParameter("1988bund");
	  }
	  else if (urlaub.equals("1989bund") )
	  {
		 path = getServletConfig().getInitParameter("1989bund");
	  }
	  else if (urlaub.equals("1989dolomiten") )
	  {
		 path = getServletConfig().getInitParameter("1989dolomiten");
	  }
	  else if (urlaub.equals("1991gardasee") )
	  {
		 path = getServletConfig().getInitParameter("1991gardasee");
	  }
	  else if (urlaub.equals("1992dolomiten") )
	  {
		 path = getServletConfig().getInitParameter("1992dolomiten");
	  }
	  else if (urlaub.equals("1994clermontFerrand") )
	  {
		 path = getServletConfig().getInitParameter("1994clermontFerrand");
	  }
	  else if (urlaub.equals("1994piemont") )
	  {
		 path = getServletConfig().getInitParameter("1994piemont");
	  }
	  else if (urlaub.equals("1995irland") )
	  {
		 path = getServletConfig().getInitParameter("1995irland");
	  }
	  
	  dirContent.execute(bilderRoot,path);
	  //dirContent.setPathName(path);
	  //dirContent.execute();
   
	  String firstpicture = new String();
	  /*
	  int i=0;
	  do
	  {
	    firstpicture = dirContent.getPathFileObject().listFiles()[i].getName();
	    i++;
	  }
	  while (!ActualPicture.isValidPictureFile(firstpicture));  
	  */  
	  //ActualPicture actualPicture = new ActualPicture(dirContent.getPathFileObject().listFiles()[i-1].getPath());
	  ActualPicture actualPicture = new ActualPicture();
	  //actualPicture.execute(bilderRoot, dirContent.getAllPicturePaths(i-2));
	  actualPicture.execute(dirContent, dirContent.getAllPicturePaths(0));
	  session.setAttribute("actualPicture", actualPicture);
	  
	  urlaubViewBean.execute(request);  	  
	  
	  // Call the output page. If the output page is not passed
	  // as part of the URL, the default page is called.

	  //callPage(getPageNameFromRequest(request), request, response);
   	  response.sendRedirect(getServletConfig().getInitParameter("ResultPage"));

	}

	catch (Throwable theException)
	{
	  // uncomment the following line when unexpected exceptions are occuring to aid in debugging the problem
	  theException.printStackTrace();

	  //handleError(request, response, theException);
	}
	
  }                                                                                              
}
